"""task_template_id_nullable

Revision ID: 0863b14bcffb
Revises: 5d4f705a08c9
Create Date: 2026-07-17 08:50:59.651748

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0863b14bcffb"
down_revision: Union[str, Sequence[str], None] = "5d4f705a08c9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "task_instance", "task_template_id", existing_type=sa.UUID(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "task_instance", "task_template_id", existing_type=sa.UUID(), nullable=False
    )
    # ### end Alembic commands ###
