"""Init

Revision ID: 5d4f705a08c9
Revises:
Create Date: 2026-07-17 08:48:39.053138

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5d4f705a08c9"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "outbox",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=255), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox")),
    )
    op.create_table(
        "task_instance",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("public_id", sa.String(length=8), nullable=False),
        sa.Column("task_template_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("occurrence_date", sa.Date(), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "COMPLETED", "CANCELLED", "MISSED", name="taskstatus"),
            nullable=False,
        ),
        sa.Column("postpone_reason", sa.String(), nullable=True),
        sa.Column("reminded_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task_instance")),
        sa.UniqueConstraint("public_id", name=op.f("uq_task_instance_public_id")),
        sa.UniqueConstraint(
            "task_template_id", "occurrence_date", name="uq_task_template_per_day"
        ),
    )
    op.create_index(
        op.f("ix_task_instance_occurrence_date"),
        "task_instance",
        ["occurrence_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_task_instance_scheduled_at"),
        "task_instance",
        ["scheduled_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_task_instance_task_template_id"),
        "task_instance",
        ["task_template_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_task_instance_user_id"), "task_instance", ["user_id"], unique=False
    )
    op.create_table(
        "task_template",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("public_id", sa.String(length=8), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("trigger", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task_template")),
        sa.UniqueConstraint("public_id", name=op.f("uq_task_template_public_id")),
    )
    op.create_index(
        op.f("ix_task_template_user_id"), "task_template", ["user_id"], unique=False
    )
    op.create_table(
        "user",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("telegram_user_id", sa.Integer(), nullable=False),
        sa.Column("timezone", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user")),
        sa.UniqueConstraint("telegram_user_id", name=op.f("uq_user_telegram_user_id")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user")
    op.drop_index(op.f("ix_task_template_user_id"), table_name="task_template")
    op.drop_table("task_template")
    op.drop_index(op.f("ix_task_instance_user_id"), table_name="task_instance")
    op.drop_index(op.f("ix_task_instance_task_template_id"), table_name="task_instance")
    op.drop_index(op.f("ix_task_instance_scheduled_at"), table_name="task_instance")
    op.drop_index(op.f("ix_task_instance_occurrence_date"), table_name="task_instance")
    op.drop_table("task_instance")
    op.drop_table("outbox")
    # ### end Alembic commands ###
