name: CI

on:
  push:
  pull_request:

permissions:
  contents: read
  packages: write

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: astral-sh/setup-uv@v8.1.0

      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - run: uv sync --dev

      - run: uv run pre-commit run --all-files

      - run: uv run pytest

  build:
    needs: checks

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push image
        run: |
          IMAGE="ghcr.io/${{ github.repository }}"
          IMAGE=$(echo "$IMAGE" | tr '[:upper:]' '[:lower:]')

          docker build -t "$IMAGE:latest" .
          docker push "$IMAGE:latest"

  deploy:
    needs: build
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            IMAGE="ghcr.io/${{ github.repository }}"
            IMAGE=$(echo "$IMAGE" | tr '[:upper:]' '[:lower:]')

            podman pull "$IMAGE:latest"


            podman rm -f life-scheduler-telegram-bot
            podman rm -f life-scheduler-apscheduler
            podman rm -f life-scheduler-alembic

            podman run -d \
              --name life-scheduler-telegram-bot \
              --env-file /home/life-scheduler/.env \
              --restart unless-stopped \
              --network=host \
              "$IMAGE:latest"

            podman run -d \
              --name life-scheduler-apscheduler \
              --env-file /home/life-scheduler/.env \
              --restart unless-stopped \
              --network=host \
              --entrypoint /app/.venv/bin/python \
              "$IMAGE:latest" \
              -m entrypoints.scheduler

            podman run \
              --name life-scheduler-alembic \
              --env-file /home/life-scheduler/.env \
              --network=host \
              --entrypoint /app/.venv/bin/alembic \
              "$IMAGE:latest" \
              upgrade head
